#!/usr/bin/env python3
"""Session recorder — renders the live transcript to a readable Markdown file.

Wired to three events in settings.json:

  SessionStart  emits a digest of the previous session as additional context,
                so a developer returning to the project is back in context
                without re-reading anything.
  Stop          re-renders the current transcript after every assistant turn,
                so the file is current even if the session is never closed.
  SessionEnd    final render.

Reads the real transcript JSONL rather than reconstructing from hook payloads:
assistant prose appears in neither UserPromptSubmit nor PostToolUse, so a
reconstruction would silently lose half the exchange.

Configuration: .claude/session-recording.json
  { "enabled": true, "paused": false, "output_dir": "docs/sessions",
    "redact": ["extra regex"], "max_tool_chars": 220 }
"""
from __future__ import annotations
import json, os, re, sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULTS = {
    "enabled": False,
    "paused": False,
    "output_dir": "docs/sessions",
    "redact": [],
    "max_tool_chars": 220,
    "digest_lines": 60,
}

REDACT = [
    (re.compile(r"sk-ant-[A-Za-z0-9\-_]{20,}"), "[redacted:anthropic-key]"),
    (re.compile(r"\bAKIA[0-9A-Z]{16}\b"), "[redacted:aws-key-id]"),
    (re.compile(r"gh[pousr]_[A-Za-z0-9]{36,}"), "[redacted:github-token]"),
    (re.compile(r"xox[baprs]-[0-9A-Za-z\-]{10,}"), "[redacted:slack-token]"),
    (re.compile(r"eyJ[A-Za-z0-9\-_]{10,}\.eyJ[A-Za-z0-9\-_]{10,}\.[A-Za-z0-9\-_]{10,}"),
     "[redacted:jwt]"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"), "[redacted:private-key]"),
]


def load_config(project: Path) -> dict:
    """Project config first, then the devkit reached via CLAUDE_PLUGIN_ROOT.

    In a workspace the doctrine lives in one repository, so its settings do
    too — nothing is duplicated at the workspace root.
    """
    cfg = dict(DEFAULTS)
    candidates = [project / ".claude" / "session-recording.json"]
    if root := os.environ.get("CLAUDE_PLUGIN_ROOT"):
        candidates.append(Path(root) / "session-recording.json")
    for f in candidates:
        if f.is_file():
            try:
                cfg.update(json.loads(f.read_text()))
            except json.JSONDecodeError:
                pass
            break
    return cfg


def scrub(text: str, extra: list[str]) -> str:
    for pattern, repl in REDACT:
        text = pattern.sub(repl, text)
    for raw in extra:
        try:
            text = re.sub(raw, "[redacted]", text)
        except re.error:
            pass
    return text


def blocks(content) -> list[dict]:
    return content if isinstance(content, list) else []


def render(transcript: Path, cfg: dict) -> str:
    limit = cfg["max_tool_chars"]
    out: list[str] = []
    started = None

    for line in transcript.read_text(errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError:
            continue
        msg = row.get("message") or {}
        role = msg.get("role")
        if started is None:
            started = row.get("timestamp")

        if role == "user":
            content = msg.get("content")
            text = content if isinstance(content, str) else "\n".join(
                b.get("text", "") for b in blocks(content) if b.get("type") == "text")
            text = text.strip()
            # Tool results come back as user turns; they are not what was said.
            if not text or text.startswith("<"):
                continue
            out.append(f"\n### 🧑 Developer\n\n{text}\n")

        elif role == "assistant":
            for b in blocks(msg.get("content")):
                if b.get("type") == "text" and b.get("text", "").strip():
                    out.append(f"\n### 🤖 Claude\n\n{b['text'].strip()}\n")
                elif b.get("type") == "tool_use":
                    name = b.get("name", "?")
                    arg = json.dumps(b.get("input") or {}, ensure_ascii=False)
                    if len(arg) > limit:
                        arg = arg[:limit] + "…"
                    out.append(f"\n> 🔧 `{name}` — `{arg}`\n")

    header = [
        "<!-- Generated by .claude/hooks/session-recorder.py — do not hand-edit. -->",
        f"# Session — {started or 'unknown start'}",
        "",
        f"Rendered {datetime.now(timezone.utc).isoformat(timespec='seconds')}.",
        "Secrets matching the recorder's patterns are redacted; that is a net,",
        "not a guarantee. Read before sharing.",
        "",
    ]
    return scrub("\n".join(header) + "".join(out) + "\n", cfg["redact"])


def digest(out_dir: Path, current: Path, cfg: dict) -> str | None:
    files = sorted((p for p in out_dir.glob("*.md")
                    if p.name != "INDEX.md" and p != current),
                   key=lambda p: p.stat().st_mtime, reverse=True)
    if not files:
        return None
    tail = files[0].read_text(errors="replace").splitlines()[-cfg["digest_lines"]:]
    return (f"Previous session transcript: `{files[0]}`.\n"
            "Tail of that session, for context:\n\n" + "\n".join(tail))


def write_index(out_dir: Path) -> None:
    rows = sorted((p for p in out_dir.glob("*.md") if p.name != "INDEX.md"),
                  key=lambda p: p.name, reverse=True)
    lines = ["# Session transcripts", "",
             "Generated by the session recorder. Newest first.", ""]
    lines += [f"- [{p.stem}]({p.name})" for p in rows]
    (out_dir / "INDEX.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    try:
        event = json.load(sys.stdin)
    except Exception:
        return 0

    project = Path(os.environ.get("CLAUDE_PROJECT_DIR") or event.get("cwd") or ".")
    cfg = load_config(project)
    if not cfg["enabled"] or cfg["paused"]:
        return 0

    transcript = event.get("transcript_path")
    session = (event.get("session_id") or "unknown")[:8]
    out_dir = project / cfg["output_dir"]
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{datetime.now().strftime('%Y-%m-%d')}-{session}.md"

    if event.get("hook_event_name") == "SessionStart":
        text = digest(out_dir, target, cfg)
        if text:
            print(json.dumps({"hookSpecificOutput": {
                "hookEventName": "SessionStart", "additionalContext": text}}))
        return 0

    if not transcript or not Path(transcript).is_file():
        return 0
    target.write_text(render(Path(transcript), cfg))
    write_index(out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
